# Port config
server.port=8080

# Logging Configurations
logging.level.org.springframework=info
logging.level.com.cognizant=debug
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Database connection (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:week2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Batch Processing Configuration (EMS Exercise 10)
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# SQL initialization mode to load data.sql on startup
spring.sql.init.mode=always

# Enable bean overriding
spring.main.allow-bean-definition-overriding=true

# Defer data.sql execution until Hibernate has created the tables
spring.jpa.defer-datasource-initialization=true

